"""Enumerations shared across ORM models.

All enums are plain ``str`` subclasses of ``enum.Enum`` so that:
  * they serialize cleanly to/from JSON in API layers built on top of these
    models (Tasks 6+), and
  * the underlying database column stores the lowercase ``.value`` (via
    ``values_callable``) rather than the Python member name.
"""

from enum import Enum


class PreferredNotificationMethod(str, Enum):
    """How a Customer prefers to be reached (also reused as Notification.notification_type,
    i.e. the delivery channel a given notification was actually sent through)."""

    EMAIL = "email"
    SMS = "sms"
    PUSH = "push"
    IN_APP = "in_app"


class DeviceStatus(str, Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    MAINTENANCE = "maintenance"
    OFFLINE = "offline"


class BatteryStatus(str, Enum):
    """Coarse battery-health bucket for a Device, per the source spec's `BatteryStatus` field."""

    OK = "ok"
    LOW = "low"
    CRITICAL = "critical"


class SessionStatus(str, Enum):
    ACTIVE = "active"
    ENDED = "ended"


class TicketStatus(str, Enum):
    OPEN = "open"
    IN_PROGRESS = "in_progress"
    RESOLVED = "resolved"
    CLOSED = "closed"


class Priority(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class AccessLevel(str, Enum):
    """SupportAgent access tiers per ASS3 Sec 3.6."""

    TIER_1 = "tier_1"
    TIER_2 = "tier_2"
    ADMIN = "admin"


class DrivingEventType(str, Enum):
    """Matches the event categories generated by Task 5's synthetic data generator."""

    SPEEDING = "speeding"
    HARSH_BRAKING = "harsh_braking"
    IDLING = "idling"
    ROUTE_DEVIATION = "route_deviation"


class ChatMessageRole(str, Enum):
    """Who authored a given `ChatMessage`: the customer's own question, or
    the AI assistant's (or escalation fallback's) response."""

    USER = "user"
    ASSISTANT = "assistant"
