/**
 * TypeScript mirrors of the Pydantic response models in
 * `backend/app/api/telematics.py` (`DriverOut`, `VehicleOut`, `TripOut`).
 * Field names/nullability were copied directly from that file, not
 * guessed -- keep these in sync if the backend schemas change.
 */

export interface Driver {
  driver_id: number
  customer_id: number
  full_name: string
  license_number: string
  email: string | null
  phone_number: string | null
  created_at: string
}

export interface Vehicle {
  vehicle_id: number
  customer_id: number
  registration_number: string
  make: string
  model: string
  year: number
  created_at: string
}

export interface Trip {
  trip_id: number
  driver_id: number
  vehicle_id: number
  start_time: string
  end_time: string | null
  start_location: string | null
  end_location: string | null
  distance_km: number | null
  created_at: string
}

/**
 * Matches the `DrivingEventType` enum in `backend/app/models/enums.py`
 * exactly (values, not guessed names) -- see that file's docstring: "Matches
 * the event categories generated by Task 5's synthetic data generator."
 */
export type DrivingEventType = 'speeding' | 'harsh_braking' | 'idling' | 'route_deviation'

export interface DrivingEvent {
  driving_event_id: number
  trip_id: number
  event_type: DrivingEventType
  event_time: string
  location: string | null
  details: string | null
  created_at: string
}

/**
 * Matches the `TicketStatus` enum in `backend/app/models/enums.py` exactly
 * (values, not guessed names).
 */
export type TicketStatus = 'open' | 'in_progress' | 'resolved' | 'closed'

/** Matches the `Priority` enum in `backend/app/models/enums.py`. */
export type Priority = 'low' | 'medium' | 'high' | 'urgent'

/**
 * Matches the `PreferredNotificationMethod` enum in
 * `backend/app/models/enums.py` (also reused as `Notification.notification_type`).
 */
export type NotificationType = 'email' | 'sms' | 'push' | 'in_app'

/**
 * Mirrors `SupportTicketOut` in `backend/app/api/chat.py` (Task 20's
 * `GET /tickets` endpoint). Field names/nullability copied directly from
 * that file, not guessed.
 */
export interface SupportTicket {
  support_ticket_id: number
  chat_session_id: number
  customer_id: number
  device_id: number
  assigned_support_agent_id: number | null
  ticket_status: TicketStatus
  priority: Priority
  subject: string | null
  description: string | null
  created_at: string
  resolved_at: string | null
}

/**
 * Mirrors `NotificationOut` in `backend/app/api/chat.py` (Task 20's
 * `GET /notifications` endpoint). Field names/nullability copied directly
 * from that file, not guessed.
 */
export interface Notification {
  notification_id: number
  support_ticket_id: number
  customer_id: number
  notification_type: NotificationType
  message: string
  sent_at: string | null
  created_at: string
}

/**
 * Matches the `DeviceStatus` enum in `backend/app/models/enums.py` exactly.
 */
export type DeviceStatus = 'active' | 'inactive' | 'maintenance' | 'offline'

/**
 * Matches the `BatteryStatus` enum in `backend/app/models/enums.py` exactly.
 */
export type BatteryStatus = 'ok' | 'low' | 'critical'

/**
 * Mirrors `DeviceOut` in `backend/app/api/telematics.py` (`GET /devices`,
 * Task 7). Field names/nullability copied directly from that file, not
 * guessed. Used by `ChatWidget` (Task 21) to resolve a `device_id` when
 * starting a new `/chat` session -- see that component's docstring.
 */
export interface Device {
  device_id: number
  customer_id: number
  serial_number: string
  device_type: string
  battery_status: BatteryStatus
  signal_strength: number | null
  last_seen: string | null
  device_status: DeviceStatus
  installed_at: string | null
  created_at: string
}
