"""add customer_id fk to driver and vehicle for fleet isolation

Revision ID: 054e88c6af09
Revises: f047842cb6ff
Create Date: 2026-08-19 23:14:06.877100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054e88c6af09'
down_revision: Union[str, Sequence[str], None] = 'f047842cb6ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Both FK adds are wrapped in batch mode: SQLite (the dev/test fallback used
    # when a live Postgres+pgvector instance isn't available -- see Task 4's
    # report) has no ALTER TABLE ADD CONSTRAINT support, so adding a FK to an
    # already-existing table requires Alembic's copy-and-move batch strategy.
    # Batch mode is a passthrough on Postgres (`recreate="auto"` only recreates
    # on SQLite), so this runs unchanged there. Plain integer FKs (unlike the
    # native-enum battery_status column added in f047842cb6ff) need no other
    # Postgres-specific handling.
    with op.batch_alter_table('drivers') as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_drivers_customer_id_customers', 'customers', ['customer_id'], ['customer_id']
        )
    # NOTE: autogenerate also proposed an `alter_column` modifying
    # knowledge_base_articles.embedding from NUMERIC(precision=768) to
    # VECTOR(dim=768). That is a false positive caused by SQLite's type-affinity
    # reflection losing pgvector's custom type name on round-trip (see Task 4's
    # report) -- the column has been VECTOR(768) since migration 482fedba36a5 and
    # never actually changed, so that op was deliberately dropped from this revision.
    with op.batch_alter_table('vehicles') as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_vehicles_customer_id_customers', 'customers', ['customer_id'], ['customer_id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles') as batch_op:
        batch_op.drop_constraint('fk_vehicles_customer_id_customers', type_='foreignkey')
        batch_op.drop_column('customer_id')
    with op.batch_alter_table('drivers') as batch_op:
        batch_op.drop_constraint('fk_drivers_customer_id_customers', type_='foreignkey')
        batch_op.drop_column('customer_id')
    # ### end Alembic commands ###
