"""initial schema

Revision ID: 482fedba36a5
Revises: 
Create Date: 2026-08-19 15:16:28.763845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '482fedba36a5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector before creating any table with a VECTOR column.
    # (Manually added -- autogenerate cannot detect extension requirements.)
    # Guarded to Postgres only: SQLite (used as a test/dev fallback where a
    # live Postgres+pgvector instance isn't available -- see backend/tests/
    # test_models.py and the task report for details) has no CREATE EXTENSION.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=False),
    sa.Column('preferred_notification_method', sa.Enum('email', 'sms', 'push', 'in_app', name='preferred_notification_method'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('drivers',
    sa.Column('driver_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('driver_id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('knowledge_base_articles',
    sa.Column('knowledge_base_article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('knowledge_base_article_id')
    )
    op.create_table('support_agents',
    sa.Column('support_agent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('access_level', sa.Enum('tier_1', 'tier_2', 'admin', name='access_level'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('support_agent_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registration_number', sa.String(length=32), nullable=False),
    sa.Column('make', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=64), nullable=False),
    sa.Column('device_status', sa.Enum('active', 'inactive', 'maintenance', 'offline', name='device_status'), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_location', sa.String(length=255), nullable=True),
    sa.Column('end_location', sa.String(length=255), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('chat_sessions',
    sa.Column('chat_session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('session_status', sa.Enum('active', 'ended', name='session_status'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ),
    sa.PrimaryKeyConstraint('chat_session_id')
    )
    op.create_table('driving_events',
    sa.Column('driving_event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('speeding', 'harsh_braking', 'idling', 'route_deviation', name='driving_event_type'), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('details', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('driving_event_id')
    )
    op.create_table('support_tickets',
    sa.Column('support_ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_support_agent_id', sa.Integer(), nullable=True),
    sa.Column('ticket_status', sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticket_status'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='priority'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_support_agent_id'], ['support_agents.support_agent_id'], ),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_sessions.chat_session_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.PrimaryKeyConstraint('support_ticket_id'),
    sa.UniqueConstraint('chat_session_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('support_ticket_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('email', 'sms', 'push', 'in_app', name='preferred_notification_method'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ),
    sa.ForeignKeyConstraint(['support_ticket_id'], ['support_tickets.support_ticket_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('support_tickets')
    op.drop_table('driving_events')
    op.drop_table('chat_sessions')
    op.drop_table('trips')
    op.drop_table('devices')
    op.drop_table('vehicles')
    op.drop_table('support_agents')
    op.drop_table('knowledge_base_articles')
    op.drop_table('drivers')
    op.drop_table('customers')
    # ### end Alembic commands ###
