"""add device telemetry fields and support_ticket device fk

Revision ID: f047842cb6ff
Revises: 482fedba36a5
Create Date: 2026-08-19 15:26:30.108689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f047842cb6ff'
down_revision: Union[str, Sequence[str], None] = '482fedba36a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # `battery_status` needs special handling vs. autogenerate's naive
    # op.add_column(..., sa.Enum(...)): when SQLAlchemy creates a whole table
    # (as it did for devices.device_status back in 482fedba36a5's
    # op.create_table), it automatically emits `CREATE TYPE ... AS ENUM (...)`
    # as part of that DDL sequence. A bare op.add_column() on an
    # *already-existing* table does NOT trigger that -- on Postgres this would
    # fail with `type "battery_status" does not exist` when the ALTER TABLE ...
    # ADD COLUMN references a native enum type that was never created. Create
    # the type explicitly first, then add the column against it. On the
    # SQLite dev/test fallback (no live Postgres in this sandbox -- see Task
    # 4's report) there is no native enum type at all: sa.Enum degrades to a
    # CHECK-constrained VARCHAR added via a plain ADD COLUMN, so no separate
    # type-creation step applies there.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        battery_status_enum = postgresql.ENUM("ok", "low", "critical", name="battery_status")
        battery_status_enum.create(bind, checkfirst=True)
        op.add_column(
            "devices",
            sa.Column(
                "battery_status", battery_status_enum, nullable=False, server_default="ok"
            ),
        )
    else:
        op.add_column(
            "devices",
            sa.Column(
                "battery_status",
                sa.Enum("ok", "low", "critical", name="battery_status"),
                nullable=False,
                server_default="ok",
            ),
        )
    op.add_column('devices', sa.Column('signal_strength', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # NOTE: autogenerate also proposed an `alter_column` modifying
    # knowledge_base_articles.embedding from NUMERIC(precision=768) to
    # VECTOR(dim=768). That is a false positive caused by SQLite's type-affinity
    # reflection losing pgvector's custom type name on round-trip (see Task 4's
    # report) -- the column has been VECTOR(768) since migration 482fedba36a5 and
    # never actually changed, so that op was deliberately dropped from this revision.
    # Wrapped in batch mode: SQLite (the dev/test fallback used when a live
    # Postgres+pgvector instance isn't available -- see Task 4's report) has no
    # ALTER TABLE ADD CONSTRAINT support, so adding a FK to an existing table
    # requires Alembic's copy-and-move batch strategy. Batch mode is a no-op
    # passthrough on Postgres (`recreate="auto"` only recreates on SQLite), so
    # this runs unchanged there.
    with op.batch_alter_table('support_tickets') as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_support_tickets_device_id_devices', 'devices', ['device_id'], ['device_id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets') as batch_op:
        batch_op.drop_constraint('fk_support_tickets_device_id_devices', type_='foreignkey')
        batch_op.drop_column('device_id')
    op.drop_column('devices', 'last_seen')
    op.drop_column('devices', 'signal_strength')
    op.drop_column('devices', 'battery_status')
    # Drop the native enum type only on Postgres (symmetric with the explicit
    # .create() in upgrade() -- SQLite never had a standalone type to drop).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        postgresql.ENUM(name="battery_status").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
